// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zSubscription.Entities.QuangTT.Models;

public partial class MembershipFeeQuangTt
{
    public int MembershipFeeQuangTtid { get; set; }

    public string MemberName { get; set; }

    public decimal Amount { get; set; }

    public DateTime PaymentDate { get; set; }

    public string PaymentMethod { get; set; }

    public string TransactionCode { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Notes { get; set; }

    public int? Status { get; set; }

    public DateTime? PublishDate { get; set; }

    public DateTime? UpdateAt { get; set; }

    public int? FeePackageQuangTtid { get; set; }

    public bool IsActive { get; set; }

    public virtual FeePackageQuangTt FeePackageQuangTt { get; set; }
}
